spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: ljc-auth
          uri: lb://ljc-auth
          predicates:
            - Path=/ljc-auth/**
        - id: ljc-r
          uri: lb://ljc-resource-server
          predicates:
            - Path=/ljc-resource-server/**