spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: ljc-auth
          uri: lb://ljc-auth
          predicates:
            - Path=/ljc-auth/**
        - id: ljc-member
          uri: lb://ljc-member
          predicates:
            - Path=/ljc-member/**
        - id: ljc-product
          uri: lb://ljc-product
          predicates:
            - Path=/ljc-product/**